### ISSUE TITLE
OCUpdater detects VirtualSMC wrong version and always offers an upgrade

### ISSUE THREAD

**Issue by perez987** [Lovely-XPP/OCUpdater#3]
Good night.

All existing kexts in my EFI folders are well detected by OCUpdater with the right version but VirtualSMC is detected as 0.3.1 instead of the right 1.3.1 and the script always says that there is an update available. I type UA, kext is updated, no error message but, after that, it shows again version 0.3.1 and update available.
I can't find 0.3.1 nowhere.

OCUpdater outputs this about VirtualSMC in the kexts info:

```bash
VirtualSMC
     [Remote Version]  1.3.1 (2022-08-06 14:34:12)
     [Local Version]   0.3.1 (2021-11-07 12:01:24)
     [Installed Kexts]   
		   SMCRadeonGPU.kext
		   SMCSuperIO.kext
		   SMCProcessor.kext
		   VirtualSMC.kext
     [Status]  Update Available
```

But VirtualSMC really is 1.3.1, as seen in file info:

<img width="263" alt="vsmc info" src="https://user-images.githubusercontent.com/50429399/201423039-e461bc49-1f1e-444f-8c12-85bfa3b77c7f.png">

And also in Contents/Info.plist:

<img width="597" alt="vsmc info plist" src="https://user-images.githubusercontent.com/50429399/201423125-62d4b1a5-9d7f-40bf-92db-0ee380505a25.png">

**Comment by perez987** [comment]
Noticed that removing the specific code for the kext:
```python
           # VirtualSMC
            if kext0[0:3].upper() == 'SMC' or kext0.upper() == 'VIRTUALSMC':
                try: 
                    local['VirtualSMC']['kexts'].append(kext)
                except:
                    plist_name = os.path.join(kext_full, 'Contents/Info.plist')
                    with open(plist_name, 'rb') as pl:
                        plist = load(pl)
                        ver = plist['CFBundleVersion']
                        pl.close()
                    time = self.get_time(plist_name)
                    local['VirtualSMC'] = {'time': time, 'version': ver, 'kexts': [kext]}
                continue
```
 keeping only the generic code:

```python
            # in kexts_list: save time and kext name
            plist_name = os.path.join(kext_full, 'Contents/Info.plist')
            with open(plist_name, 'rb') as pl:
                plist = load(pl)
                ver = plist['CFBundleVersion']
                pl.close()
            time = self.get_time(plist_name)
            local[kext0] = {'time': time, 'version': ver, 'kexts': [kext]}
        return local
```
VirtualSMC version is ok and OCUpdater doesn't offer any update and seems to run fine.

**Comment by Lovely-XPP** [comment]
Sorry about that, I will check the code later. The specific code is needed, because VirtualSMC is not a kext, but a package with many kexts. So I need to collect the local kext that have installed before, so that update the kexts only installed.

**Comment by perez987** [comment]
Last code has fixed this, now VirtualSMC version is ok and it says `Kexts: Up-to-date`. Thanks.

```bash
VirtualSMC
     [Remote Version]  1.3.1 (2022-08-06 14:34:12)
     [Local Version]   1.3.1 (2022-11-10 19:39:16)
     [Installed Kexts]   
		   SMCRadeonGPU.kext
		   SMCSuperIO.kext
		   SMCProcessor.kext
		   VirtualSMC.kext
     [Status]  Up-to-date
```

**Comment by Lovely-XPP** [comment]
Thanks for your feedback :)
